apiVersion: v1
kind: ConfigMap
metadata: 
  name: otel-collector-conf
  namespace: otel-collector
  labels: 
    app: otel 
    component: otel-collector-conf
data: 
  otel-collector-config: |
    receivers: 
      otlp: 
        protocols: 
          grpc:
            keepalive:
              server_parameters:
                max_connection_idle: 11s
                max_connection_age: 12s
                max_connection_age_grace: 13s
                time: 30s
                timeout: 5s
              enforcement_policy:
                min_time: 10s
                permit_without_stream: true
            max_recv_msg_size_mib: 32
            max_concurrent_streams: 16
            read_buffer_size: 1024
            write_buffer_size: 1024
      prometheus: 
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 5s
              static_configs:
                - targets: ['otel-collector.otel-collector:8888']
            - job_name: 'linkerd'
              kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names: ['python-app', 'otel-collector', 'otel-exporters']
              scrape_interval: 5s
              static_configs:
                - targets: ['linkerd-prometheus.linkerd:9090'] #INFO: Pulls data from linkerD prometheus 
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape, __meta_kubernetes_pod_container_name]
                  regex: "true"
                  action: keep
              metric_relabel_configs:
                - source_labels: [__name__]
                  regex: "(request_duration_seconds.*|response_duration_seconds.*)"
                  action: keep
              honor_labels: true
              metrics_path: '/federate'
              params:
                'match[]':
                  - '{job="linkerd-proxy"}'
                  - '{job="linkerd-controller"}'
    exporters: 
      file: 
        path: ./exported.json
      logging:
        loglevel: debug
      # prometheus:
      #   endpoint: prometheus.otel-exporters:9090
      #   const_labels:
      #     app: python_app
      #   send_timestamps: true
      jaeger:
        endpoint:  jaeger.otel-exporters:14250
        insecure: true
    extensions:
      health_check:
      zpages:
        endpoint: 0.0.0.0:55679
      pprof:
    service:
      extensions: [health_check, zpages, pprof]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [file, jaeger, logging]
        metrics:
          receivers: [otlp]
          exporters: [file, logging]
      
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otel-collector
  labels:
    app: otel 
    component: otel-collector
spec:
  ports:
  - name: otlp-grpc # grpc endpoint for OpenTelemetry receiver.
    port: 4317
  - name: otlp-http # http endpoint for OpenTelemetry receiver.
    port: 55681
  - name: jaeger-grpc # default endpoint for Jaeger gRPC receiver
    port: 14250
  - name: jaeger-thrift-http # default endpoint for Jaeger HTTP receiver.
    port: 14268
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: otel-collector

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel-collector
  labels:
    app: otel
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: otel
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: otel
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
          # Memory Ballast size should be max 1/3 to 1/2 of memory.
          #- "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector:latest
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 4317 # grpc endpoint for OpenTelemetry receiver.
        - containerPort: 55681 # HTTP Endpoint for OpenTelemetry receiver.
        - containerPort: 14250 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 55679 # Default endpoint for ZPages extensions
        - containerPort: 1777 # pprof extension 
        - containerPort: 13133 # healthcheck extension 

        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
#        - name: otel-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol