apiVersion: v1
kind: ConfigMap
metadata: 
  name: otel-agent-conf
  namespace: otel-collector
  labels: 
    app: otel 
    component: otel-agent-conf
data: 
  otel-agent-config: |
    receivers: 
      otlp: 
        protocols: 
          grpc: 
            keepalive:
              server_parameters:
                max_connection_idle: 11s
                max_connection_age: 12s
                max_connection_age_grace: 13s
                time: 30s
                timeout: 5s
              enforcement_policy:
                min_time: 10s
                permit_without_stream: true
            max_recv_msg_size_mib: 32
            max_concurrent_streams: 16
            read_buffer_size: 1024
            write_buffer_size: 1024
      hostmetrics: 
        collection_interval: 30s 
        scrapers: 
          cpu:
          disk:
          load: 
          memory: 
          processes: 
          process:  
    extensions:
      health_check:
      zpages:
      pprof:
    exporters: 
      otlp: 
        insecure: true
        endpoint: otel-collector.otel-collector:4317 
    service:
      extensions: [health_check, zpages, pprof]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp, hostmetrics]
          exporters: [otlp]



---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: otel-collector
  labels:
    app: otel
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: otel
      component: otel-agent
  template:
    metadata:
      labels:
        app: otel
        component: otel-agent
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-agent-config.yaml"
          # Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=165"
        image: otel/opentelemetry-collector:latest
        name: otel-agent
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 55679 # ZPages endpoint.
        - containerPort: 4317 # grpc endpoint for OpenTelemetry receiver.
        - containerPort: 55681 # HTTP Endpoint for OpenTelemetry receiver.
        - containerPort: 8888  # Metrics.
        - containerPort: 13133 # Health check
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol