apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: otel-exporters
  labels:
    app: jaeger
spec:
  selector: 
    matchLabels:
      app: jaeger
  replicas: 1
  template: 
    metadata:
      labels:
        app: jaeger
    spec: 
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
          - containerPort: 5775
          - containerPort: 6831
          - containerPort: 6832
          - containerPort: 5778
          - containerPort: 16686 # http /api/* & UI https://www.jaegertracing.io/docs/1.21/deployment/#query-service--ui
          - containerPort: 14268 # http receiver
          - containerPort: 14269 # health check at / and /metrics
          - containerPort: 14250 # grpc receiver
          - containerPort: 9411 # zipkin

---
apiVersion: v1
kind: Service
metadata:
  labels: 
      app: jaeger
  name: jaeger 
  namespace: otel-exporters
spec:
  selector:
    app: jaeger
  type: LoadBalancer
  ports:
  - name: query
    port: 16686 # http /api/* & UI https://www.jaegertracing.io/docs/1.21/deployment/#query-service--ui
  - name: http-receiver
    port: 14268 # http receiver
  - name: healthcheck
    port: 14269 # health check at / and /metrics
  - name: grpc-receiver
    port: 14250 # grpc receiver
  - name: zipkin
    port: 9411 # zipkin